### ISSUE TITLE
Plug-in Addition

### ISSUE THREAD

**Issue by tmbutterworth** [CodeDraken/ES-Hub#3]
I have a plug-in on github called hand-to-hand outfits https://github.com/tmbutterworth/hand-to-hand-outfits. I would like to add it to ES-Hub. If this is not the right place for the request please let me know who to send it too.

**Comment by CodeDraken** [comment]
If it's an in-game plugin then I believe you mean to add it on the mod share repo:

https://github.com/OpenGameMods-group/ES-Mod-Share

You can find the steps for submitting a plugin on that page or in the readme.

**Comment by tmbutterworth** [comment]
Thank you for you assistance.
